# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container:
  image: ros:dashing-ros-core
  options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"

steps:
  - script: |
      /tmp/docker exec -t -u 0 ci-container \
      sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
    displayName: Set up sudo

  - script: |
      rosdep update
      rosdep install --from-paths . --ignore-src -y
    displayName: 'Set Up Environment'

  - script: sudo apt-get install -y python3-colcon-common-extensions
    displayName: 'Install colcon'
    
  - script: |
      source /opt/ros/dashing/setup.bash
      colcon build \
        --cmake-args \
          -DCMAKE_BUILD_TYPE=Release
    displayName: 'Build'

  - script: |
      source /opt/ros/dashing/setup.bash
      colcon test
      colcon test-result --verbose
    displayName: 'Test'
